# Generated by Django 4.1.7 on 2023-03-31 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balanceapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(default='Balance', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_hidden', models.BooleanField(default=False)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('icon', models.CharField(default='fa fa-money', max_length=50)),
                ('wallet_category', models.CharField(choices=[('0', 'Income'), ('1', 'Expense')], default='0', max_length=1)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_balance', to='balanceapp.balance')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
